[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = [
  "pydantic-ai",
  "pydantic",
  "duckdb",
  "pandas",
  "httpx",
  "pyyaml",
  "streamlit",
  "ruamel-yaml"
]
description = "Configurable literature tracker for academic journals, using Pydantic AI"
name = "paper-agent"
requires-python = ">=3.10"
version = "0.1.0"

[project.scripts]
paper-agent = "paper_agent.main:main"
paper-agent-ui = "web_ui.main:main"

[tool.deptry]
known_first_party = ["paper_agent", "web_ui"]

[tool.deptry.package_module_name_map]
pyyaml = "yaml"
ruamel-yaml = "ruamel"

[tool.hatch.build.targets.wheel]
packages = ["src/paper_agent", "src/web_ui"]

[tool.uv]
dev-dependencies = [
  "pytest",
  "ruff"
]
